# Generated by Django 3.2.8 on 2022-01-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon ')),
                ('message', models.CharField(max_length=250, verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'Contactlar',
            },
        ),
    ]
