# Generated by Django 3.2.8 on 2022-01-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
