# Generated by Django 3.2.8 on 2022-01-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_maincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincart',
            name='all_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maincart',
            name='carts',
            field=models.ManyToManyField(blank=True, to='main.Cart', verbose_name='carts'),
        ),
    ]
