# Generated by Django 3.2.8 on 2022-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220130_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='all_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mkv',
            field=models.FloatField(verbose_name='m kvadrat'),
        ),
        migrations.AlterField(
            model_name='maincart',
            name='all_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
